### ISSUE TITLE
Error in set_layoutSizingHorizontal on version 25

### ISSUE THREAD

**Issue by mrksoftware** [ergon/figma-table-builder#10]
Hi,
Starting from version 25 we started having this issue while creating a table starting from a cell component:

![image](https://github.com/ergon/figma-table-builder/assets/7292153/31849a7a-ae60-4fb3-a46d-85412d6fd9b8)

With a previous forked version everything works fine on the same component.
I had a similar issue in the past on my forked version and it was due to the fact I was using `layoutSizingHorizontal` too soon, before the `appendChild` on that node.. I don't know if that can help

The issue appears only if wrap in auto layout is enabled

Please, let me know if you need any further info

**Comment by mrksoftware** [comment]
Nevermind, we found the issue and it was in our component!

As you added a few new lines that were setting the `layoutSizingHorizontal` on the `textNode` object, the text layer in figma must be a direct child of an auto-layout for this to work, and in our case there was an inner container which wasn't.. once we modified this container, it started working again!

![image](https://github.com/ergon/figma-table-builder/assets/7292153/c7439a19-bcef-4857-aa31-fc46fb4f4e47)

Hope this can help someone in the future in case they have any issue and maybe as an enhancement it could be nice to display an error message since at the moment it is only visible through the development console

I let you close it in case you want to handle this as a separate issue

**Comment by NatashaDudi** [comment]
Thanks for being so invested! I included a bugfix for this in our latest update. Can you check if it works for you now?
