### ISSUE TITLE
No way to update data

### ISSUE THREAD

**Issue by OscarGodson** [ergon/figma-table-builder#4]
As far as I can tell there isn't a way to replace the data with new data. It'd save a lot of time for me since I've been using this and often will make a component out of a table so it updates everywhere. However, I'll have more than one "variation" such as a filtered down table or what not. Currently, I don't see a way to update the data though so I have to do this from scratch and update all components if I need to update the data.

**Comment by Landschaft** [comment]
Hi @OscarGodson and thank you for opening this issue. I've obviously never used the plugin for updating tables, but thinking about it, such a feature would make a lot of sense.

So, if I understand you correctly, you would like to have a workflow like:

1. Use **Table Builder** to create a table
2. Turn the created table into component
3. Create an instance of the table component
4. Use **Table Builder** to override the instance's contents

Is that what you'd like to have? If not, please describe your own workflow.

**Comment by OscarGodson** [comment]
Replacing the instance itself is a nice but the workflow is more like this @Landschaft 

1. Use Table Builder to create a table
2. Turn the created table into component
3. Right click on it -> Plugins -> Table Builder -> Update Data
4. Update the data just like if I were building a new table with that little textarea box

That way the data is then updated across all instances. Overriding particular instances would be a nice touch but the previous example would save me the most time. Unfortunately, right now I have for example 4 variations of my "table component". I get new data and I have to then build a brand new table from scratch and recreate the component and variations. Since I have prototypes attached to this (like sorting) it makes it pretty painful as i have to recreate the animations and such as well.

**Comment by Landschaft** [comment]
We've published a new version 23 of the plugin that allows for updating tables.

@OscarGodson you might want to try if this speeds up your workflow

**Comment by OscarGodson** [comment]
Excellent I'll give it a shot! Thanks for following up.

**Comment by Landschaft** [comment]
@OscarGodson we'd love to hear your feedback

**Comment by Landschaft** [comment]
@OscarGodson have you been able to test the new feature? I close this issue now.

**Comment by OscarGodson** [comment]
Oh yes! Forgot to update. It works great. I super appreciate it!
